### ISSUE TITLE
Connection Guide Updates Required

### ISSUE THREAD

**Issue by DocSunset** [IDMIL/T-Stick#17]
The [connection guide](https://github.com/IDMIL/T-Stick/blob/master/Docs/T-Stick_2GW_Connecting_Guide(v1.2).md) doesn't necessarily reflect the details of newer wireless T-Sticks. The differences are not especially problematic or significant, but it does create an unsettling feeling as I set up the T-Stick on my desk.

- My T-Stick has no power switch. How am I meant to power it on?
- If my battery is dead, how will I know?
- My T-Stick's setup network SSID is very different from the one shown (TStick_312 vs T-Stick_SN_black2_194).
- The setup webpage did not open automatically on my (unusually configured Arch Linux) device.consistent/simpler method that could be suggested.
- The design of the configuration page has changed and doesn't reflect the screen captures
- The T-Stick appears not to automatically switch over to the configured network and needs to be rebooted now?

I managed to figure it all out, and I've made some edits to the connection guide to help anyone after, but a more formal update may be in order, by someone who knows what's going on...

**Comment by aburt2** [comment]
honestly I recon we should try to write the guides to use a little pictures as humanly possible @edumeneses I can do the updates as I've also been writing a connection guide for Torquetuner as there both Puara devices the steps are the same

**Comment by edumeneses** [comment]
I agree @aburt2 !

I'll be at IDMIL this morning. We can talk about that and also about using Puara at TorqueTuner.

**Comment by aburt2** [comment]
connection guide has been updated
