### ISSUE TITLE
fsr offset bug

### ISSUE THREAD

**Issue by takujin3** [IDMIL/T-Stick#19]
The problem is that it returns a negative value once you set the offset value. Clip the value.

**Comment by DocSunset** [comment]
It would be helpful on this and other issues if you could describe why this is a problem. There may be deeper underlying issues and more efficient solutions, but we may not be able to tell if you merely suggest a solution without describing the problem.

**Comment by aburt2** [comment]
The OSC signal for raw FSR isn't being properly calculated in the current firmware, for some reason it is outputting the raw value - offset which it did not use to do in previous versions

**Comment by aburt2** [comment]
resolved with #27
