### ISSUE TITLE
Possible License Issue

### ISSUE THREAD

**Issue by DocSunset** [IDMIL/T-Stick#30]
It appears the T-Stick firmware is marked as MIT licensed, whereas libmapper-arduino uses the stronger copyleft, and therefore incompatible, GPL 3+. I've left an issue on the latter in case this was not intended to be so (https://github.com/mathiasbredholt/libmapper-arduino/issues/11), but in case it is the T-Stick firmware probably needs to be changed to also use the GPL 3+ license. @edumeneses I'm guessing the MIT license here was inherited from the Puara template?

**Comment by edumeneses** [comment]
Thanks for pointing that out @DocSunset. 

The MIT portion mentioned in the [README](https://github.com/IDMIL/T-Stick#readme) comes from before Puara, but for the firmware folder, we have an inherited [LICENSE file](https://github.com/IDMIL/T-Stick/blob/main/firmware/LICENSE) from the Puara template.

But the [puara-module-template](https://github.com/Puara/puara-module-template) license is also wrong, as it loads Mathias' [libmapper-arduino](https://github.com/mathiasbredholt/libmapper-arduino). Finally,  [Puara-module](https://github.com/Puara/puara-module) states that it requires libmapper-arduino, but it doesn´t.

I'll fix the licensing on Puara's end: change the [puara-module-template](https://github.com/Puara/puara-module-template) to GPL3 and update the readme file for [Puara-module](https://github.com/Puara/puara-module), leaving it as MIT. 

After that, we can fix the T-Stick's licence (should be GPL3).

I think we previously discussed the licensing for libmapper and decided to go for GPL3. Not sure if that's the best option **if** we want to spread libmapper usage beyond the open source, but this is a topic for the libmapper group.

**Comment by DocSunset** [comment]
It seems like libmapper-arduino might get a license change (https://github.com/mathiasbredholt/libmapper-arduino/issues/11) so it might be better to wait for that situation to fully resolve. 👍

**Comment by edumeneses** [comment]
Ah, I see. In that case, if Mathias decides to change to LGPL, we can keep MIT.

I might change Puara's licences to LGPL soon. I'll follow up and wait a bit to update the licenses all at once when libmapper-arduino license is sorted out.

**Comment by DocSunset** [comment]
Mathias updated the upstream license to LGPL (mathiasbredholt/libmapper-arduino@54060796d08fe81d888958f7c023df5a5ffad720), so looks like this is a non-issue.
