### ISSUE TITLE
Libmapper crashes on FW211124

### ISSUE THREAD

**Issue by edumeneses** [IDMIL/T-Stick#6]
Libmapper crashes when creating signals during boot time. This is not a libmapper issue (the libmapper-Arduino example works fine).

**Comment by mathiasbredholt** [comment]
Hi @edumeneses, are you creating signals after connecting to wifi?

**Comment by edumeneses** [comment]
Yes, I checked that. I'm installing ArduinoIDE again as I had a flatpack before and couldn't decode the exception. I'll check it soon

**Comment by edumeneses** [comment]
I fixed this issue. I'll keep this open until someone tests it.
